<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Doors\roof - Copy.png" />
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
    <None Remove="Levels\Level_0\R0\Collisions-int.png" />
    <None Remove="Levels\Level_0\R0\Collisions.csv" />
    <None Remove="Levels\Level_0\R0\Collisions.png" />
    <None Remove="Levels\Level_0\R0\Custom_grounds.png" />
    <None Remove="Levels\Level_0\R0\Custom_tiles.png" />
    <None Remove="Levels\Level_0\R0\data.json" />
    <None Remove="Levels\Level_0\R0\Default_ground.png" />
    <None Remove="Levels\Level_0\R0\Wall_outlines.png" />
    <None Remove="Levels\Level_0\R0\_bg.png" />
    <None Remove="Levels\Level_0\R0\_composite.png" />
    <None Remove="Levels\Level_0\R2\Collisions-int.png" />
    <None Remove="Levels\Level_0\R2\Collisions.csv" />
    <None Remove="Levels\Level_0\R2\Collisions.png" />
    <None Remove="Levels\Level_0\R2\Custom_grounds.png" />
    <None Remove="Levels\Level_0\R2\Custom_tiles.png" />
    <None Remove="Levels\Level_0\R2\data.json" />
    <None Remove="Levels\Level_0\R2\Default_ground.png" />
    <None Remove="Levels\Level_0\R2\Wall_outlines.png" />
    <None Remove="Levels\Level_0\R2\_bg.png" />
    <None Remove="Levels\Level_0\R2\_composite.png" />
    <None Remove="Levels\Level_0\R3\Collisions.csv" />
    <None Remove="Rooms\Collisions2.csv" />
    <None Remove="Rooms\R0\Collisions2.csv" />
    <None Remove="Rooms\R0\data.json" />
    <None Remove="Rooms\R1\Collisions-int.png" />
    <None Remove="Rooms\R1\Collisions.csv" />
    <None Remove="Rooms\R1\Collisions.png" />
    <None Remove="Rooms\R1\Custom_grounds.png" />
    <None Remove="Rooms\R1\Custom_tiles.png" />
    <None Remove="Rooms\R1\data.json" />
    <None Remove="Rooms\R1\Default_ground.png" />
    <None Remove="Rooms\R1\Wall_outlines.png" />
    <None Remove="Rooms\R1\_bg.png" />
    <None Remove="Rooms\R1\_composite.png" />
    <None Remove="Rooms\R2\data.json" />
    <None Remove="Rooms\R3\data.json" />
    <None Remove="Rooms\R4\data.json" />
    <None Remove="Rooms\R5\Collisions.csv" />
    <None Remove="Rooms\R4\Collisions.csv" />
    <None Remove="Rooms\R3\Collisions.csv" />
    <None Remove="Rooms\R5\data.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LDtkMonogame" Version="1.0.1" />
    <PackageReference Include="LDtkMonogame.ContentPipeline" Version="1.0.1" />
    <PackageReference Include="MonoGame.Extended.Particles" Version="3.8.0" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Levels\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Doors\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>